// <auto-generated />
using System;
using CajaADN.Integration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CajaADN.Integration.Migrations
{
    [DbContext(typeof(CajaDbContext))]
    partial class CajaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("CajaADN.Domain.Models.InmuebleCatastro", b =>
                {
                    b.Property<string>("InmuebleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoUso")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Zona")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("InmuebleId");

                    b.ToTable("Catastro");

                    b.HasData(
                        new
                        {
                            InmuebleId = "INM-00101",
                            Direccion = "Av. Winston Churchill",
                            TipoUso = "Residencial",
                            Zona = "Piantini"
                        },
                        new
                        {
                            InmuebleId = "INM-00102",
                            Direccion = "Av. Abraham Lincoln",
                            TipoUso = "Comercial",
                            Zona = "Piantini"
                        },
                        new
                        {
                            InmuebleId = "INM-00201",
                            Direccion = "Calle Pasteur",
                            TipoUso = "Residencial",
                            Zona = "Gazcue"
                        },
                        new
                        {
                            InmuebleId = "INM-00202",
                            Direccion = "Av. Independencia",
                            TipoUso = "Comercial",
                            Zona = "Gazcue"
                        },
                        new
                        {
                            InmuebleId = "INM-00301",
                            Direccion = "Calle El Conde",
                            TipoUso = "Comercial",
                            Zona = "Zona Colonial"
                        },
                        new
                        {
                            InmuebleId = "INM-00302",
                            Direccion = "Calle Las Damas",
                            TipoUso = "Residencial",
                            Zona = "Zona Colonial"
                        });
                });

            modelBuilder.Entity("CajaADN.Domain.Models.SesionCaja", b =>
                {
                    b.Property<Guid>("IdSesion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Estado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaApertura")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FechaCierre")
                        .HasColumnType("TEXT");

                    b.Property<string>("UsuarioCajero")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdSesion");

                    b.ToTable("Sesiones");
                });

            modelBuilder.Entity("CajaADN.Domain.Models.Transaccion", b =>
                {
                    b.Property<Guid>("TransaccionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("IdSesion")
                        .HasColumnType("TEXT");

                    b.Property<int>("IntentosSincronizacion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Monto")
                        .HasColumnType("TEXT");

                    b.Property<string>("NcfSimulado")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreContribuyente")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Origen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ReferenciaId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Sincronizado")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("TimestampLocal")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimoIntentoSincronizacion")
                        .HasColumnType("TEXT");

                    b.HasKey("TransaccionId");

                    b.ToTable("Transacciones");
                });

            modelBuilder.Entity("CajaADN.Integration.Data.UsuarioEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaveHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NombreUsuario")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
