namespace CajaADN.Domain.Enums;

public enum TipoPago
{
    PAGO_ASEO_URBANO,
    PAGO_PERMISO_CONSTRUCCION,
    PAGO_CEMENTERIO,
    PAGO_RECOLECCION_ESPECIAL,
    PAGO_USO_ESPACIO_PUBLICO,
    PAGO_REGISTRO_COMERCIAL,
    PAGO_CERTIFICACION_NO_OBJECCION,
    PAGO_SOLICITUD_PODA,
    PAGO_PLACA_NUMERACION,
    PAGO_PUBLICIDAD_EXTERIOR
}